### ISSUE TITLE
How much gain did self-distillation bring?

### ISSUE THREAD

**Issue by renliao** [XiangZ-0/GEM#10]
Hello,

Thank you for your outstanding work! This is my first time encountering self-distillation applied to event-based motion deblurring, and I am very curious about the performance improvements it provides. Specifically, I would like to know what the PSNR/SSIM values would be if only a single training stage were used.

Thank you, and I look forward to your reply!

**Comment by XiangZ-0** [comment]
Hi, thanks for your question. Self-distillation is used to improve the generalization ability across spatial and temporal dimensions. We have conducted related experiments, and some results are reported in Section 4.3 of our paper, specifically models 3 (one-stage) and 6 (two-stage) in Tab. 3 and Fig. 6. Hope this helps :)

**Comment by renliao** [comment]
Thank you for your reply. I understand your work better now.
