### ISSUE TITLE
Onedrive link for Dataset, Pretrained model is not working.

### ISSUE THREAD

**Issue by Juns1105** [XiangZ-0/GEM#5]
Dear author, 

Many thanks for your notable work.

The provided onedrive link seems expired.

Could you please open the refreshed link?

Thanks in advance.

**Comment by XiangZ-0** [comment]
Hi, thank you for your interest in our work. Could you let me know more specifically which link is not working? I just re-tested these links and it seems they are still effective on my side. Thanks!

**Comment by Juns1105** [comment]
> Hi, thank you for your interest in our work. Could you let me know more specifically which link is not working? I just re-tested these links and it seems they are still effective on my side. Thanks!

I apologize for my mistake.

All the links are still available. 

Sorry for interrupting you.

Thanks!

**Comment by XiangZ-0** [comment]
No worries. Glad they still work 😊
