### ISSUE TITLE
support resume-train?

### ISSUE THREAD

**Issue by renliao** [XiangZ-0/GEM#9]
Hi, thank you for your excellent work, I want to konw if it supports resume-train? if true, what shall i do?

**Comment by XiangZ-0** [comment]
Hi, thanks for your interest in our work. To resume the training from certain checkpoints, you can add the followings below lines 32 of the [model file](https://github.com/XiangZ-0/GEM/blob/33891b3e8f362dabba46cab4a28946c6c528269c/codes/model/model_interface.py#L33):
```
pretrained_model_path = '/path/to/your/pretrained/model/'
state_dict = self.load_state_dict_from_checkpoint(pretrained_model_path)
self.model.load_state_dict(state_dict)
```
Please modify the 'pretrained_model_path' according to your environment, then it should work.
Hope this helps!

**Comment by renliao** [comment]
Thank you for your replay!
